Feature: Card opening date
  Users can see and correct the opening date of a saved card.

  Background:
    Given I have added the "Chase Sapphire Preferred" card

  Scenario: Display the saved opening date and persist a correction
    Then the card should display its original opening date
    When I open the card details editor
    Then the opening date input should contain the original opening date
    When I enter "2020-02-29" as the card opening date
    And I click "Save Changes"
    Then I should see a toast "Card updated!"
    And the card should display opening date "2020-02-29"
    And the bonus countdown should show expired
    When I open the bonus deadline editor
    Then the bonus deadline input should contain "2020-05-29"
    When I click "Cancel"
    When I reload the page
    Then the card should display opening date "2020-02-29"
    And the bonus countdown should show expired
    When I view the card detail for "Chase Sapphire Preferred"
    Then the card should display opening date "2020-02-29"
    When I open the card details editor
    Then the opening date input should contain "2020-02-29"
    And the annual fee date input should still contain the original annual fee date

  Scenario: Cancel an opening date correction
    Then the card should display its original opening date
    When I open the card details editor
    And I enter "2020-02-29" as the card opening date
    And I click "Cancel"
    Then the card should display its original opening date
    When I open the card details editor
    Then the opening date input should contain the original opening date

  Scenario: Require an opening date before saving
    When I open the card details editor
    And I enter "" as the card opening date
    Then saving the opening date should be disabled
    When I enter "2020-02-29" as the card opening date
    Then saving the opening date should be enabled

  Scenario: Reject a future opening date and allow today
    Then the card should display its original opening date
    When I open the card details editor
    And I enter "9998-01-01" as the card opening date
    Then saving the opening date should be disabled
    And the opening date input should be invalid
    When I click "Cancel"
    Then the card should display its original opening date
    When I open the card details editor
    And I enter today as the card opening date
    Then saving the opening date should be enabled
    When I click "Save Changes"
    Then I should see a toast "Card updated!"

  Scenario: Preserve a customized bonus deadline when correcting the opening date
    When I open the bonus deadline editor
    And I enter "2028-01-15" as the bonus deadline
    And I click "Save Changes"
    Then I should see a toast "Sign-up bonus updated!"
    When I open the card details editor
    And I enter "2020-02-29" as the card opening date
    And I click "Save Changes"
    Then the card should display opening date "2020-02-29"
    When I reload the page
    And I open the bonus deadline editor
    Then the bonus deadline input should contain "2028-01-15"

  Scenario: Preserve an earned bonus when correcting the opening date
    When I update the bonus spend to 100000
    Then I should see the bonus marked as complete
    When I open the card details editor
    And I enter "2020-02-29" as the card opening date
    And I click "Save Changes"
    Then the card should display opening date "2020-02-29"
    And I should see the bonus marked as complete
    When I reload the page
    Then I should see the bonus marked as complete

  Scenario: Correct an opening date with a deadline generated by an older version
    Given the card has a legacy generated bonus deadline
    When I open the card details editor
    And I enter "2021-01-15" as the card opening date
    And I click "Save Changes"
    Then the card should display opening date "2021-01-15"
    When I open the bonus deadline editor
    Then the bonus deadline input should contain "2021-04-15"
